<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>NOVORA</RootNamespace>
		<AssemblyName>NOVORA</AssemblyName>
		<Version>1.4.0</Version>
		<Platforms>AnyCPU</Platforms>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<ApplicationIcon>NOVORA_1.1.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="Tools\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Content Include="NOVORA.ico" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Tools\LinkEngine\NOVORA.LinkEngine.Relay.exe" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
		
	</ItemGroup>
	<ItemGroup>
	</ItemGroup>
	<ItemGroup>
		<None Remove="Assets\NOVORA-BRAND.png" />
		<None Remove="Assets\NOVORA-BRAND_LIGHT.png" />
		<Resource Include="Assets\NOVORA-BRAND.png" />
		<Resource Include="Assets\NOVORA-BRAND_LIGHT.png" />
	</ItemGroup>

  <ItemGroup>
    
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\PDI2T.mp4"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>


