<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<TargetFramework>net10.0-android</TargetFramework>

		<OutputType>Exe</OutputType>

		<RootNamespace>NOVORA.LinkEngine.Android</RootNamespace>

		<AssemblyName>NOVORA.LinkEngine.Android</AssemblyName>

		<ApplicationId>com.novora.linkengine</ApplicationId>

		<ApplicationTitle>NOVORA</ApplicationTitle>

		<ApplicationVersion>3</ApplicationVersion>

		<ApplicationDisplayVersion>1.4.A4</ApplicationDisplayVersion>

		<SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>

		<Nullable>enable</Nullable>

		<ImplicitUsings>enable</ImplicitUsings>

		<AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>

		<AndroidPackageFormat>apk</AndroidPackageFormat>

		<TrimMode Condition="'$(Configuration)' == 'Release'">full</TrimMode>

	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">

		<AndroidKeyStore>true</AndroidKeyStore>

		<AndroidSigningKeyStore>$(UserProfile)\.android\debug.keystore</AndroidSigningKeyStore>

		<AndroidSigningStorePass>android</AndroidSigningStorePass>

		<AndroidSigningKeyAlias>androiddebugkey</AndroidSigningKeyAlias>

		<AndroidSigningKeyPass>android</AndroidSigningKeyPass>

	</PropertyGroup>

	<!-- ============================================================ -->
	<!-- ANDROID MANIFEST PERMISSIONS                                 -->
	<!-- ============================================================ -->

	<ItemGroup>

		<AndroidManifestPlaceholders Include="novoraLinkEngine=true" />

	</ItemGroup>

</Project>
